    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="hlavniStrana">ÚVOD</a></li>
            <li class="breadcrumb-item"><a href="galerie">GALERIE</a></li>
            <li class="breadcrumb-item active" aria-current="page"><?= htmlspecialchars($nazev_alba) ?></li>
        </ol>
    </nav>

    <div class="orientnadpis">
        <div class="container">
            <div class="row">
                <div class="orientnadpisdiv col-md-12 d-flex justify-content-center align-items-center align-content-center">
                    <div class="orientnadpissam d-flex justify-content-center align-items-center align-content-center">
                        <p class="nadpisorient"><?= htmlspecialchars($nazev_alba) ?></p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="fotografie photo-gallery">
        <div class="container">
            <div class="row photos">

                <?php foreach ($seznamFotek as $fotky) : ?>
                    <div class="obb col-sm-6 col-md-4 col-lg-3 item">
                        <a data-lightbox="photos" href="<?= $fotky['cesta'] ?>">
                            <img class="obrglr img-fluid  border border-light" src="<?= $fotky['cesta'] ?>">
                        </a>
                    </div>
                    <?php if ($admin) : ?>
                        <br />
                        <a href="fotografie/<?= $fotky['url'] ?>/odstranit/<?= $fotky['id_fotografie'] ?>" onClick="return confirm('Určitě chcete odstranit fotografii?')">Odstranit</a>
                    <?php endif ?>
                <?php endforeach ?>

            </div>
        </div>
    </div>

    <script src="assets/js/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.8.2/js/lightbox.min.js"></script>