<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="hlavniStrana">ÚVOD</a></li>
        <li class="breadcrumb-item"><a href="clanek">SEZNAM ČLÁNKŮ</a></li>
        <li class="breadcrumb-item active" aria-current="page"><?= htmlspecialchars($nazev_clanku) ?></li>
    </ol>
</nav>



<div class="clanek article-clean">
    <div class="container">
        <div class="row">
            <div class="col-lg-10 col-xl-8 offset-lg-1 offset-xl-2">
                <div class="intro">
                    <p class="articlenadpis text-center"><?= htmlspecialchars($nazev_clanku) ?></p>
                    <p class="articledatum text-center">
                        <span class="date"><?php echo date("d.m.Y", strtotime($datum)); ?></span>
                    </p>
                </div>

                <div class="text">
                    <figure>
                        <img class="figure-img" src="<?= $cesta ?>">
                    </figure>
                    <span class="articletext text-center"><?= htmlspecialchars($text_clanku) ?></span>
                    
                </div>
            </div>
        </div>
    </div>
</div>