<div class="rtadmin">

    <br />
    <br />

    <h1>SEZNAM ČLENŮ</h1>

    <br />

    <div class="seznamhracu">
        <div class="container">
            <div class="row">

                <?php foreach ($clenove as $clen) : ?>

                    <div class=" rtcus col-md-3 d-flex justify-content-center align-items-center align-content-center">
                        <div class="text-center infoohraci">
                            <P><?= htmlspecialchars($clen['jmeno']) ?> <?= htmlspecialchars($clen['prijmeni']) ?></P>
                            <P><?= htmlspecialchars($clen['email']) ?></P>
                            <P><?= htmlspecialchars($clen['tel_cislo']) ?></P>
                        </div>
                    </div>

                    <div class="col-md-3">
                        <a href="editorClenu/<?= $clen['id_realizacni_tym'] ?>">Editovat</a>
                        <a href="clenove/<?= $clen['id_realizacni_tym'] ?>/odstranit" onClick="return confirm('Určitě chcete smazat člena?')">Odstranit</a>
                    </div>

                <?php endforeach ?>

            </div>
        </div>
        <?= $strankovani ?>
    </div>
</div>