<br />
<br />
<br />

<form method="post" class="edit">

	<h1>EDITOR VŠECH ČLENŮ KLUBU</h1>

	<input type="hidden" name="id_realizacni_tym" value="<?= $clen['id_realizacni_tym'] ?>" />

	<br />

	Jméno

	<br />

	<div class="form-group">
		<input type="text" name="jmeno" class="form-control my-input" value="<?= $clen['jmeno'] ?>" required/>
	</div>

	<br />
	<br />

	Příjmení

	<br />

	<div class="form-group">
		<input type="text" name="prijmeni" class="form-control my-input" value="<?= $clen['prijmeni'] ?>" required/>
	</div>

	<br />
	<br />

	Email

	<br />

	<div class="form-group">
		<input type="email" name="email" class="form-control my-input" value="<?= $clen['email'] ?>" required/>
	</div>

	<br />
	<br />

	Telefonní číslo

	<br />

	<div class="form-group">
		<input type="text" name="tel_cislo" class="form-control my-input" value="<?= $clen['tel_cislo'] ?>" required/>
	</div>

	<br />
	<br />

	<div class="text-center">
		<button type="submit" class="btn btn-block btn-warning send-button tx-tfm">ULOŽIT ČLENA</button>
	</div>

</form>

<br />
<br />