<br />
<br />
<br />

<?php $datum = $album['datum_pridani'] ?>

<form method="post" class="edit">

	<h1>EDITOR ALB</h1>

	<input type="hidden" name="id_alba" class="form-control my-input" value="<?= $album['id_alba'] ?>" />

	<br />

	Název alba

	<br />

	<div class="form-group">
		<input type="text" name="nazev_alba" class="form-control my-input" value="<?= $album['nazev_alba'] ?>" required/>
	</div>

	<br />
	<br />

	URL

	<br />

	<div class="form-group">
		<input type="text" name="url" class="form-control my-input" value="<?= $album['url'] ?>" required/>
	</div>

	<br />
	<br />

	Datum přidání

	<br />

	<div class="form-group">
		<input type="datetime-local" name="datum_pridani" class="form-control my-input" value="<?php if ($datum) {
																									echo date("Y-m-d\TH:i:s", strtotime($datum));
																								} else {
																									echo "2021-01-01T00:00";
																								} ?>" min="2021-01-01T00:00" required/>

	</div>

	<br />
	<br />

	<div class="text-center">
		<button type="submit" class="btn btn-block btn-warning send-button tx-tfm">ULOŽIT ALBUM</button>
	</div>

</form>

<br />
<br />