<br />
<br />
<br />

<form method="post" class="edit">

	<h1>EDITOR HRÁČŮ</h1>

	<input type="hidden" name="id_hraci" value="<?= $hraci['id_hraci'] ?>" />

	<br />

	Hráč

	<br />

	<div class="form-group">
		<select name="hrac" class="form-control my-input" required>
			<option value=''>Vyberte člena</option>
			<?php foreach ($seznamClenu as $clen) : ?>
				<option value="<?php echo $clen['id_realizacni_tym'] ?>" <?php if ($clen['id_realizacni_tym'] == $hraci['id_hraci'])  echo 'selected'; ?>><?= $clen['jmeno'] ?> <?= $clen['prijmeni'] ?></option>
			<?php endforeach ?>
		</select>
	</div>

	<br />
	<br />

	Post

	<br />

	<div class="form-group">
		<input type="text" name="post" class="form-control my-input" value="<?= $hraci['post'] ?>" required/>
	</div>

	<br />
	<br />

	Číslo dresu

	<br />

	<div class="form-group">
		<input type="text" name="cislo_dresu" class="form-control my-input" value="<?= $hraci['cislo_dresu'] ?>" required/>
	</div>

	<br />
	<br />

	Kategorie

	<br />

	<div class="form-group">
		<select name="kategorie" class="form-control my-input" required>
			<option value=''>Vyberte kategorii</option>
			<?php foreach ($seznamKategorii as $kategorie) : ?>
				<option value="<?php echo $kategorie['id_kategorie'] ?>" <?php if ($kategorie['id_kategorie'] == $hraci['kategorie_id'])  echo 'selected'; ?>><?= $kategorie['nazev_kategorie'] ?></option>
			<?php endforeach ?>
		</select>
	</div>

	<br />
	<br />

	<div class="text-center">
		<button type="submit" class="btn btn-block btn-warning send-button tx-tfm">ULOŽIT HRÁČE</button>
	</div>

</form>

<br />
<br />