<br />
<br />
<br />

<form method="post" class="edit">

	<h1>EDITOR TRENÉRŮ</h1>

	<input type="hidden" name="id_trenera" value="<?= $trener['id_trenera'] ?>" />

	<br />
	
	Trenér

	<br />

	<div class="form-group">
		<select name="trener" class="form-control my-input" required>
			<option value=''>Vyberte kategorii</option>
			<?php foreach ($seznamClenu as $clen) : ?>
				<option value="<?php echo $clen['id_realizacni_tym'] ?>" <?php if ($clen['id_realizacni_tym'] == $trener['id_trenera'])  echo 'selected'; ?>><?= $clen['jmeno'] ?> <?= $clen['prijmeni'] ?></option>
			<?php endforeach ?>
		</select>
	</div>

	<br />
	<br />

	Trénovaná kategorie

	<br />

	<div class="form-group">
		<select name="kategorie" class="form-control my-input" required>
			<option value=''>Vyberte kategorii</option>
			<?php foreach ($seznamKategorii as $kategorie) : ?>
				<option value="<?php echo $kategorie['id_kategorie'] ?>" <?php if ($kategorie['id_kategorie'] == $trener['id_kategorie'])  echo 'selected'; ?>><?= $kategorie['nazev_kategorie'] ?></option>
			<?php endforeach ?>
		</select>
	</div>

	<br />
	<br />

	<div class="text-center">
		<button type="submit" class="btn btn-block btn-warning send-button tx-tfm">ULOŽIT TRENÉRA</button>
	</div>

</form>

<br />
<br />