<div class="rtadmin">

    <br />
    <br />

    <h1>SEZNAM FUNKCIONÁŘŮ</h1>

    <br />

    <div class="seznamhracu">
        <div class="container">
            <div class="row">

                <?php foreach ($funkcionari as $funkcionar) : ?>

                    <div class=" rtcus col-md-3 d-flex justify-content-center align-items-center align-content-center">
                        <div class="text-center infoohraci">
                            <p><?= htmlspecialchars($funkcionar['jmeno']) ?> <?= htmlspecialchars($funkcionar['prijmeni']) ?></p>
                            <p><?= htmlspecialchars($funkcionar['pozice']) ?></p>
                        </div>
                    </div>

                    <div class="col-md-3">
                        <a href="editorFunkcionaru/<?= $funkcionar['id_clena'] ?>">Editovat</a>
                        <br />
                        <a href="funkcionari/<?= $funkcionar['id_clena'] ?>/odstranit" onClick="return confirm('Určitě chcete odebrat funkci funkcionáře?')">Odstranit</a>
                    </div>

                <?php endforeach ?>

            </div>
        </div>
    </div>
</div>